import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl p-32 text-red-100">Hello next js</h1>
      <h2 className="ml-10">yo yo</h2>
    </div>
  );
}
